// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=local/PA_API/design
// --out=$(GOPATH)\src\local\pa_api
// --version=v1.0.0
//
// API "PANOS API": Application Resource Href Factories
//
// The content of this file is auto-generated, DO NOT MODIFY

package app
