// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=local/PA_API/design
// --out=$(GOPATH)\src\local\pa_api
// --version=v1.0.0
//
// API "PANOS API": keygen TestHelpers
//
// The content of this file is auto-generated, DO NOT MODIFY

package test

import (
	"bytes"
	"fmt"
	"github.com/goadesign/goa"
	"github.com/goadesign/goa/goatest"
	"golang.org/x/net/context"
	"io"
	"local/pa_api/app"
	"log"
	"net/http"
	"net/http/httptest"
	"net/url"
)

// GetKeygenOK runs the method Get of the given controller with the given parameters.
// It returns the response writer so it's possible to inspect the response headers.
// If ctx is nil then context.Background() is used.
// If service is nil then a default service is created.
func GetKeygenOK(t goatest.TInterface, ctx context.Context, service *goa.Service, ctrl app.KeygenController, password *string, user *string) http.ResponseWriter {
	// Setup service
	var (
		logBuf bytes.Buffer
		resp   interface{}

		respSetter goatest.ResponseSetterFunc = func(r interface{}) { resp = r }
	)
	if service == nil {
		service = goatest.Service(&logBuf, respSetter)
	} else {
		logger := log.New(&logBuf, "", log.Ltime)
		service.WithLogger(goa.NewLogger(logger))
		newEncoder := func(io.Writer) goa.Encoder { return respSetter }
		service.Encoder = goa.NewHTTPEncoder() // Make sure the code ends up using this decoder
		service.Encoder.Register(newEncoder, "*/*")
	}

	// Setup request context
	rw := httptest.NewRecorder()
	query := url.Values{}
	if password != nil {
		sliceVal := []string{*password}
		query["password"] = sliceVal
	}
	if user != nil {
		sliceVal := []string{*user}
		query["user"] = sliceVal
	}
	u := &url.URL{
		Path:     fmt.Sprintf("/api/keygen"),
		RawQuery: query.Encode(),
	}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		panic("invalid test " + err.Error()) // bug
	}
	prms := url.Values{}
	if password != nil {
		sliceVal := []string{*password}
		prms["password"] = sliceVal
	}
	if user != nil {
		sliceVal := []string{*user}
		prms["user"] = sliceVal
	}
	if ctx == nil {
		ctx = context.Background()
	}
	goaCtx := goa.NewContext(goa.WithAction(ctx, "KeygenTest"), rw, req, prms)
	getCtx, err := app.NewGetKeygenContext(goaCtx, service)
	if err != nil {
		panic("invalid test data " + err.Error()) // bug
	}

	// Perform action
	err = ctrl.Get(getCtx)

	// Validate response
	if err != nil {
		t.Fatalf("controller returned %s, logs:\n%s", err, logBuf.String())
	}
	if rw.Code != 200 {
		t.Errorf("invalid response status code: got %+v, expected 200", rw.Code)
	}

	// Return results
	return rw
}
